# Production docker-compose with additional security and monitoring
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.main
    ports:
      - "8080:8080"
    environment:
      - DO_API_TOKEN=${DO_API_TOKEN}
      - REDIS_URL=redis:6379
      - MAIN_SERVER_IP=${MAIN_SERVER_IP}
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    networks:
      - nuclei-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - nuclei-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - nuclei-network

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  nuclei-network:
    driver: bridge
