version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.simple
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - nuclei-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - nuclei-network
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local

networks:
  nuclei-network:
    driver: bridge
