version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.main
    ports:
      - "8080:8080"
    environment:
      - DO_API_TOKEN=${DO_API_TOKEN}
      - REDIS_URL=redis:6379
      - MAIN_SERVER_IP=${MAIN_SERVER_IP:-localhost}
      - PORT=8080
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    networks:
      - nuclei-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - nuclei-network

  # Optional: Redis GUI for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - nuclei-network
    profiles:
      - debug

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  nuclei-network:
    driver: bridge
